# A config file for DNN tests on Office Home dataset
#
# @Time    : 2022/12/26 14:23
# @Author  : 
# @Notes   : Baseline tests. 
# 

name = 'sourceonly'      # where to save the results under ./saved/
trainer = 'BasicTrainer' # the trainer name; main procedure

# ############################## Resume
# resume = "saved/office_home_Pr_Rw_source_only/2023-02-24-16-45-10/model/model_best.pth"
# resume = "saved/office_home_Pr_Rw_source_only_SGD/2023-02-27-16-38-00/model/model_best.pth"


############################### Important hyper parameters!!
label_smoothing = 0.15


############################### Miscellaneous
epochs = 20
num_classes = 6
save_period = 2
# Whether to plot the confusion matrices in each test epoch to ./saved/**/confusion/*.jpg.
plot_confusion = true

############################### Entropy
# fbnm = false
# rowsparse = false
# entropy = false

# onm = false
# balance = false

############################### Neural Networks
# The base model
[model]
name = 'WiSigSHOTNet'
args = { num_classes = 6 }

############################### Dataloaders
# On source domian
[dataloader_train]
args = { batch_size = 128, num_workers = 1, shuffle = true, drop_last = true }
[dataloader_train.dataset]
name = "WiSigDiffRecvDataset"
args = { Rx = ['14-7'], train = true }

[dataloader_test]
args = { batch_size = 128, num_workers = 1, shuffle = false, drop_last = true }
[dataloader_test.dataset]
name = "WiSigDiffRecvDataset"
args = { Rx = ['3-19'], train = false }

############################### Learning Rate Schedulers for Optimizers
[lr_scheduler]
name = "StepLR"
init_lr = 0.0001
args = { step_size = 5000, gamma = 0.6 }

